### Llistar tots els conflictes
GET http://localhost:8080/api/v1/conflicts

###

### Filtrar per estat ACTIVE
GET http://localhost:8080/api/v1/conflicts?status=ACTIVE

###

### Conflictes d'un país per codi
GET http://localhost:8080/api/v1/countries/UKR/conflicts