GET http://localhost:8080/api/v1/conflicts

###

GET http://localhost:8080/api/v1/conflicts?status=ACTIVE

###

GET http://localhost:8080/api/v1/countries/UKR/conflicts

###

PUT http://localhost:8080/api/v1/conflicts/1
Content-Type: application/json

{
  "name": "Conflicte Actualitzat",
  "status": "INACTIVE"
}

###

DELETE http://localhost:8080/api/v1/conflicts/1